name: React Vite CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: docker
    container:
      image: node:25-trixie

    steps:
      - name: Install dependencies
        run: |
          # Use npm, yarn, or pnpm based on your project
          npm ci --prefer-offline
          # Alternative: yarn install --frozen-lockfile
          # Alternative: pnpm install --frozen-lockfile

      - name: Type check (if using TypeScript)
        run: npx tsc --noEmit

      - name: Lint code
        run: npm run lint || echo "No lint script found"

      - name: Run tests
        run: npm test -- --passWithNoTests || echo "No tests found"

      - name: Build project
        run: npm run build
