name: React Vite CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: docker
    container:
      image: node:25-trixie

    steps:
      - name: Install dependencies
        run: |
          git clone https://codeberg.org/KusamaShield/Interface/ && cd Interface/ && npm install -f 
#      - name: Balance rpc checks
#        run: cd Interface && npm run check_balance

      - name: Building repo
        run: cd Interface && npm run build
  
