/*
 * Copyright 2025 Kusama Shield Developers on behalf of the Kusama DAO, see LICENSE in main folder.
 */

import { WagmiAdapter } from "@reown/appkit-adapter-wagmi";
import { defineChain } from "viem";

// Read Project ID from environment variables (Vite uses VITE_ prefix)
export const projectId = import.meta.env.VITE_WALLETCONNECT_PROJECT_ID;

if (!projectId) {
  console.warn(
    "VITE_WALLETCONNECT_PROJECT_ID is not defined. EVM wallet connections may not work properly."
  );
}

// Define custom chains that match your NETWORKS config
export const kusamaAssetHub = defineChain({
  id: 420420418,
  name: "Kusama Asset Hub",
  nativeCurrency: {
    name: "Kusama",
    symbol: "KSM",
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ["https://eth-asset-hub-kusama.dotters.network/"],
    },
  },
  blockExplorers: {
    default: {
      name: "Blockscout",
      url: "https://blockscout-kusama-asset-hub.parity-chains-scw.parity.io",
    },
  },
});

export const westendAssetHub = defineChain({
  id: 420420421,
  name: "Westend Asset Hub",
  nativeCurrency: {
    name: "Westend",
    symbol: "WND",
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ["https://westend-asset-hub-eth-rpc.polkadot.io"],
    },
  },
  blockExplorers: {
    default: {
      name: "Blockscout",
      url: "https://blockscout-asset-hub.parity-chains-scw.parity.io",
    },
  },
  testnet: true,
});

export const paseoAssetHub = defineChain({
  id: 420420422,
  name: "Paseo Asset Hub",
  nativeCurrency: {
    name: "Paseo",
    symbol: "PAS",
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ["https://testnet-passet-hub-eth-rpc.polkadot.io"],
    },
  },
  blockExplorers: {
    default: {
      name: "Blockscout",
      url: "https://blockscout-passet-hub.parity-testnet.parity.io",
    },
  },
  testnet: true,
});

export const moonbaseAlpha = defineChain({
  id: 1287,
  name: "Moonbase Alpha",
  nativeCurrency: {
    name: "DEV",
    symbol: "DEV",
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ["https://moonbase.public.curie.radiumblock.co/http"],
    },
  },
  blockExplorers: {
    default: {
      name: "Moonscan",
      url: "https://moonbase.moonscan.io",
    },
  },
  testnet: true,
});

export const shibuya = defineChain({
  id: 81,
  name: "Shibuya",
  nativeCurrency: {
    name: "Shibuya",
    symbol: "SBY",
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ["https://evm.shibuya.astar.network"],
    },
  },
  blockExplorers: {
    default: {
      name: "Subscan",
      url: "https://shibuya.subscan.io",
    },
  },
  testnet: true,
});

// All supported networks
export const networks = [
  kusamaAssetHub,
  westendAssetHub,
  paseoAssetHub,
  moonbaseAlpha,
  shibuya,
];

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  projectId: projectId || "",
  networks: networks as any,
});

// Export the Wagmi config generated by the adapter
export const wagmiConfig = wagmiAdapter.wagmiConfig;
