wget https://ff.io/assets/images/coins/svg/aaveeth.svg
wget https://ff.io/assets/images/coins/svg/ada_dark.svg
wget https://ff.io/assets/images/coins/svg/apt_dark.svg
wget https://ff.io/assets/images/coins/svg/arb.svg
wget https://ff.io/assets/images/coins/svg/atom_dark.svg
wget https://ff.io/assets/images/coins/svg/avax.svg
wget https://ff.io/assets/images/coins/svg/bat.svg
wget https://ff.io/assets/images/coins/svg/bch.svg
wget https://ff.io/assets/images/coins/svg/bnbopbnb.svg
wget https://ff.io/assets/images/coins/svg/bsc.svg
wget https://ff.io/assets/images/coins/svg/wbnbbsc.svg
wget https://ff.io/assets/images/coins/svg/wbnbopbnb.svg
wget https://ff.io/assets/images/coins/svg/btc.svg
wget https://ff.io/assets/images/coins/svg/btcbsc.svg
wget https://ff.io/assets/images/coins/svg/btcln.svg
wget https://ff.io/assets/images/coins/svg/btt_dark.svg
wget https://ff.io/assets/images/coins/svg/cake.svg
wget https://ff.io/assets/images/coins/svg/daibsc.svg
wget https://ff.io/assets/images/coins/svg/daieth.svg
wget https://ff.io/assets/images/coins/svg/daimatic.svg
wget https://ff.io/assets/images/coins/svg/dash.svg
wget https://ff.io/assets/images/coins/svg/doge.svg
wget https://ff.io/assets/images/coins/svg/dot.svg
wget https://ff.io/assets/images/coins/svg/eos.svg
wget https://ff.io/assets/images/coins/svg/etc.svg
wget https://ff.io/assets/images/coins/svg/eth_dark.svg
wget https://ff.io/assets/images/coins/svg/etharbitrum_dark.svg
wget https://ff.io/assets/images/coins/svg/ethbase_dark.svg
wget https://ff.io/assets/images/coins/svg/ethbsc_dark.svg
wget https://ff.io/assets/images/coins/svg/ethop_dark.svg
wget https://ff.io/assets/images/coins/svg/ethzksync_dark.svg
wget https://ff.io/assets/images/coins/svg/wetharbitrum_dark.svg
wget https://ff.io/assets/images/coins/svg/wethbase_dark.svg
wget https://ff.io/assets/images/coins/svg/wetheth_dark.svg
wget https://ff.io/assets/images/coins/svg/ftm.svg
wget https://ff.io/assets/images/coins/svg/kcs.svg
wget https://ff.io/assets/images/coins/svg/link.svg
wget https://ff.io/assets/images/coins/svg/ltc.svg
wget https://ff.io/assets/images/coins/svg/manaeth.svg
wget https://ff.io/assets/images/coins/svg/mkr.svg
wget https://ff.io/assets/images/coins/svg/paxgeth.svg
wget https://ff.io/assets/images/coins/svg/pepeeth.svg
wget https://ff.io/assets/images/coins/svg/pol.svg
wget https://ff.io/assets/images/coins/svg/poleth.svg
wget https://ff.io/assets/images/coins/svg/s.svg
wget https://ff.io/assets/images/coins/svg/shib.svg
wget https://ff.io/assets/images/coins/svg/shibbsc.svg
wget https://ff.io/assets/images/coins/svg/sol.svg
wget https://ff.io/assets/images/coins/svg/wsol.svg
wget https://ff.io/assets/images/coins/svg/sui.svg
wget https://ff.io/assets/images/coins/svg/ton.svg
wget https://ff.io/assets/images/coins/svg/trx.svg
wget https://ff.io/assets/images/coins/svg/tusd.svg
wget https://ff.io/assets/images/coins/svg/twtbsc.svg
wget https://ff.io/assets/images/coins/svg/usdcarbitrum.svg
wget https://ff.io/assets/images/coins/svg/usdcbsc.svg
wget https://ff.io/assets/images/coins/svg/usdceth.svg
wget https://ff.io/assets/images/coins/svg/usdcmatic.svg
wget https://ff.io/assets/images/coins/svg/usdcsol.svg
wget https://ff.io/assets/images/coins/svg/usdp.svg
wget https://ff.io/assets/images/coins/svg/usdt.svg
wget https://ff.io/assets/images/coins/svg/usdtarbitrum.svg
wget https://ff.io/assets/images/coins/svg/usdtbsc.svg
wget https://ff.io/assets/images/coins/svg/usdtmatic.svg
wget https://ff.io/assets/images/coins/svg/usdtsol.svg
wget https://ff.io/assets/images/coins/svg/usdttrc.svg
wget https://ff.io/assets/images/coins/svg/vet.svg
wget https://ff.io/assets/images/coins/svg/xlm_dark.svg
wget https://ff.io/assets/images/coins/svg/xmr.svg
wget https://ff.io/assets/images/coins/svg/xrp.svg
wget https://ff.io/assets/images/coins/svg/xtz.svg
wget https://ff.io/assets/images/coins/svg/zec.svg
wget https://ff.io/assets/images/coins/svg/zrx_dark.svg
